version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EXPO_PUBLIC_SIGNAL_WS_URL=${EXPO_PUBLIC_SIGNAL_WS_URL}
    restart: always 